import turtle as tr
tr.speed(100)
def circle(r):
    tr.pendown()
    for i in range(120):
        tr.left(3)
        tr.forward(r)
def semicircle(r):
    tr.pendown()
    for i in range(60):
        tr.left(3)
        tr.forward(r)
tr.begin_fill()
circle(4)
tr.color('yellow')
tr.end_fill()
tr.color('blue')
tr.penup()
tr.goto(30, 100)
tr.begin_fill()
circle(0.3)
tr.end_fill()
tr.penup()
tr.goto(-30, 100)
tr.begin_fill()
circle(0.3)
tr.end_fill()
tr.penup()
tr.goto(0, 80)
tr.right(90)
tr.pendown()
tr.width(7)
tr.forward(30)
tr.penup()
tr.goto(-30, 50)
tr.color('red')
semicircle(1.6)
